### ISSUE TITLE
HUD do not show during flight. 

### ISSUE THREAD

**Issue by ExoY** [jrbudda/KerbalEngineer#1]
Hello, 
i installed KSP as well as your latest KerbalEngineer Version yesterday. 
It works fine while building vehicals, but I dont have any HUD's during flight. 
(The KER-Logo is displayed on the right, but i cannot click it). 
Are there any settings I need to make to enable the hud, or might that be a bug? 
Regards

**Comment by jrbudda** [comment]
Career mode? did you bring a KER part?

**Comment by jungfaha** [comment]
test

**Comment by ExoY** [comment]
Thanks for the quick reply. Since I just started my Tracking Station isnt Lvl 3 yet, so that might be the issue :) I'll know more in a couple hours when i have to time to continue my career.

**Comment by ExoY** [comment]
It worked, thanks jungfaha.

**Comment by jungfaha** [comment]
glad it worked :)
