### ISSUE TITLE
VAB/action Group window

### ISSUE THREAD

**Issue by SchizoSchaf** [jrbudda/KerbalEngineer#10]
The KER window closes if I enter the action group window inside the VAB/SPH. Not really a bug but would be nice if it stays open and gets a dry mass display as well.

Useful for some other mods like RealChutes (setup for the chutes is made inside the action groups screen).

Dry mass would be useful to know how many parachutes I have to attach for reusable stages. Atm I have 2 windows open always (mechjeb shows only dry mass) but I really prefer the engineer window.

**Comment by jrbudda** [comment]
Should be easy enough to change

**Comment by jrbudda** [comment]
See if this does it for ya without exploding anything.
[KerbalEngineer.zip](https://github.com/jrbudda/KerbalEngineer/files/1956692/KerbalEngineer.zip)

**Comment by SchizoSchaf** [comment]
Stays on screen now. Don´t get any errors. Great!
