### ISSUE TITLE
With ExtraSolar KER is not capable of showing the target celestial bodies correctly

### ISSUE THREAD

**Issue by Gordon-Dry** [jrbudda/KerbalEngineer#11]
See https://i.imgur.com/OrZ4GVp.png

There was nothing specific written to the log as I opened the UI and went back to the target selection, but here is the log whatsoever:
https://www.dropbox.com/s/wm9t2gpiopfpmx4/2018-05-02_3%20KSP.log.7z?dl=1

**Comment by jrbudda** [comment]
Where were you in the solar system when it did this? I'm sitting on the runway at KSC and it just shows Valentine and the stock planets.

**Comment by Gordon-Dry** [comment]
In Sun orbit after leaving Kerbin SOI.

**Comment by jrbudda** [comment]
Oh ok, I didn't realize you were also playing OPM. I did notice the duplication but thought those extra planets were from extrasolar. So I think I've got it worked out and also added some labels to the target selector

https://gyazo.com/10273b612725672e3cbb3cf684548a72
