### ISSUE TITLE
KerbalEngineer.version needs URL update

### ISSUE THREAD

**Issue by mlheur** [jrbudda/KerbalEngineer#12]
The .version file supplied with KER contains a URL 1.3 version file.  One suggestion is to provide the URL to this repo.

[LOG 21:54:44.148] MiniAVC -> S:\SSD Games\Modded KSP 1.4.3\GameData\KerbalEngineer\KerbalEngineer.version
	NAME: Kerbal Engineer Redux
	URL: **http://ksp-avc.cybutek.net/version.php?id=6**
	DOWNLOAD: NULL
	GITHUB: NULL
	VERSION: 1.1.4.10
	KSP_VERSION: 1.4.2
	KSP_VERSION_MIN: 1.4
	KSP_VERSION_MAX: 1.4.9
	CompatibleKspVersion: False
	CompatibleKspVersionMin: True
	CompatibleKspVersionMax: True
	CompatibleGitHubVersion: True
[LOG 21:54:44.148] MiniAVC -> http://ksp-avc.cybutek.net/version.php?id=6
	NAME: Kerbal Engineer Redux
	URL: http://ksp-avc.cybutek.net/version.php?id=6
	DOWNLOAD: http://kerbal.curseforge.com/projects/kerbal-engineer-redux
	GITHUB: NULL
	VERSION: 1.1.3
	**KSP_VERSION: 1.3
	KSP_VERSION_MIN: 1.2.9
	KSP_VERSION_MAX: 1.3.1**
	CompatibleKspVersion: False
	CompatibleKspVersionMin: True
	CompatibleKspVersionMax: False
	CompatibleGitHubVersion: True
	UpdateAvailable: False

**Comment by jrbudda** [comment]
fixed
