### ISSUE TITLE
No info for rendezvous in Tracking Center

### ISSUE THREAD

**Issue by TheWildDefender** [jrbudda/KerbalEngineer#17]
When I open up the Tracking Center and open up KER to find an interplanetary transfer window, there is no info available. However, rendezvous info is present if I am piloting a spacecraft. I have already tried removing all other mods, but the problem seems to be in KER. 

Here is a screenshot:
![screenshot_2018-06-01_21-37-20](https://user-images.githubusercontent.com/39847614/40870049-011436c6-65e4-11e8-9504-42f82aa523b7.png)

**Comment by jrbudda** [comment]
Are you setting the ship as the reference?

**Comment by TheWildDefender** [comment]
No. Kerbin is the reference orbit. I have even tried setting the ship as the reference, which did not fix the problem. There is also no information if I set the ship as the reference and target one of Kerbin's moons.

**Comment by jrbudda** [comment]
OK I think I got it sorted. See if this fixes everything. Thanks for the report.
[KerbalEngineer-1.1.5.1.zip](https://github.com/jrbudda/KerbalEngineer/files/2065617/KerbalEngineer-1.1.5.1.zip)

**Comment by TheWildDefender** [comment]
It works! I can now see the rendezvous information in the Tracking Center. If you are going to release that as a new version, should I download the mod from the main page, or can I just keep that file?

Thanks for all of your hard work!

**Comment by jrbudda** [comment]
it'll be the same file

**Comment by DpEpsilon** [comment]
Noticed the same problem, is fixed for me too.
