### ISSUE TITLE
1.1.5.3 beta test

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/KerbalEngineer#22]
1.1.5.3, 2018-7-27, KSP 1.4.5 #2243
 - Total overhaul of impact and suicide burn calculations.
 - Added impact marker to map and flight view. Toggleable via the Impact Marker readout button.
 - Add suicide burn countdown and burn length readouts.
 - Add minimum safe orbtial altitude readout.
 - Change a number of default sections and readouts. Will only apply to a clean install.

[KerbalEngineer-1.1.5.3.zip](https://github.com/jrbudda/KerbalEngineer/files/2236367/KerbalEngineer-1.1.5.3.zip)

**Comment by linuxgurugamer** [comment]
You shouldn't update the main .version file until it's released, now everyone is getting notification that there is a new version available when it's not

**Comment by nlsn** [comment]
I would like to know there's a beta available, but yeah, I was confused when the message said a new version is available but 1.1.5.2 is the latest on the releases page.

**Comment by jrbudda** [comment]
Oh balls I forgot that thing looks at the github version file.
