### ISSUE TITLE
KER whines about unsupported game version when running 1.5.0 of KSP

### ISSUE THREAD

**Issue by Jacalz** [jrbudda/KerbalEngineer#25]
Please update with support for KSP 1.5 so the game doesn't complain every start. The mod works fine though 👍

**Comment by jrbudda** [comment]
Thanks I hadn't noticed ksp updated today.

**Comment by Jacalz** [comment]
No problem, happy to help 👍

**Comment by jrbudda** [comment]
Updated

**Comment by Jacalz** [comment]
Thanks for maintaining this mod, you are doing a great job! 👍
