### ISSUE TITLE
New career, no vessel yet, tracking station issue with KER

### ISSUE THREAD

**Issue by Gordon-Dry** [jrbudda/KerbalEngineer#3]
I get a lot of those:
```
KerbalEngineer -> DisplayStackTS->Window // Object reference not set to an instance of an object
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

KerbalEngineer ->   at MapObject.GetName () [0x00000] in <filename unknown>:0 
  at MapObject.GetDisplayName () [0x00000] in <filename unknown>:0 
  at KerbalEngineer.Flight.Readouts.Rendezvous.RendezvousProcessor.nameForTargetable (ITargetable tgt) [0x00000] in <filename unknown>:0 
  at KerbalEngineer.TrackingStation.DisplayStackTS.Window (Int32 windowId) [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```
It looks like this:
https://i.imgur.com/putBEhF.png

Log: https://www.dropbox.com/s/727cjcjfnbsf22v/2018-04-07_1%20KSP.log.7z?dl=1

**Comment by jrbudda** [comment]
This is... actually a stock game issue! wonderful.

**Comment by Gordon-Dry** [comment]
Hmm. "Wonderful" because I dared to post it - how could I know?
Or "wonderful" because it shows the nitty ways of the stock game to make us humble?

btw I just have seen it also happens when vessels exist ... ;)

**Comment by jungfaha** [comment]
Perhaps just a stock issue.. and "wonderful" as in another bug from the base game. -_-

**Comment by jrbudda** [comment]
This should be fixed in 1148

**Comment by jungfaha** [comment]
oh perhaps a miscommunication. I was actually backing up jrbudda referring to the issues the base game has. any way jrbudda, thank you for your time and effort :) It's individuals such as ur self whom inspired me to start learning git bash and how to use github :)
