### ISSUE TITLE
window gone in VAB

### ISSUE THREAD

**Issue by ysu2** [jrbudda/KerbalEngineer#39]
I've just updated to the latest version (1.1.6.0) via ckan, and my KER window has disappeared from VAB (the main window showing all the buttons & delta-v).   

Additionally, the "vessel" details got borked up, too.

I've reverted back to v1.1.5.7 and all is dandy.
Using ksp v1.6.1

**Comment by jrbudda** [comment]
1.1.6.0 was built against ksp 1.7.0, I didnt test it on 1.6.1, No idea why it would break. Will test now.

**Comment by jrbudda** [comment]
I have duplicated the problem and still have no idea what is wrong. Updating the CKAN version to min 1.7.0 for now.

**Comment by ysu2** [comment]
Yeah, works perfectly well for me, too, once the ksp version is updated to 1.7.     
That's the workaround :)
