### ISSUE TITLE
Missing files to compile project 

### ISSUE THREAD

**Issue by TonkaCrash** [jrbudda/KerbalEngineer#41]
I downloaded 1.1.6 source code and it's missing 4 files needed to successfully compile KER:

..\Flight\Readouts\Orbital\CurrentSoi.cs
..\Flight\Readouts\Vessel\SuicideBurnProcessor.cs
..\UIControls\DropDown.cs
..\UIControls\WindowObject.cs

**Comment by jrbudda** [comment]
It's not the files. One of the .csproj files was being ignored by git. Try it again.

**Comment by TonkaCrash** [comment]
Thanks, I had to turn on all files in the project and add a bunch that weren't included. I'm still relatively new to using C# and Visual Studio, so this didn't occur to me. Closing this issue
