### ISSUE TITLE
Text Becomes Unreadable

### ISSUE THREAD

**Issue by Homer-S** [jrbudda/KerbalEngineer#45]
Take a look here: https://forum.kerbalspaceprogram.com/index.php?/topic/17833-130-kerbal-engineer-redux-1130-2017-05-28/page/177/&tab=comments#comment-3642433

Anyone have an issue with the text going wonky? It was working fine under 1.7.3 and then all of a sudden the window in the editor cannot be resized/moved and it is about half the size it needs to be so it becomes unreadable. At the same time, the in-flight HUDs are about half the right width and are four times taller. Makes it super hard to read.

https://lh3.googleusercontent.com/xBeNvU7BuTnjucohR9xXSWl1DkP2oGGRq_6AtkdrDRjGDIclGpq3fB3w8dha41rliNFMFeIYe0Oxdvnlz2xlYcThsNvVwiBtnmp2-W7fSERrJMHdP3sgbU3Wyi9VSXvgzahMTz_k_A=w1695-h953-no

https://lh3.googleusercontent.com/HFXkUtMgK9PSCXLef9W55depAmx31OqBvnp_h2YVOjIOZc1VK1P6V5LHb77Lju0De7imtAYuIspRsgveJMdLeihr6gFw7TfLcSLRt8UDoiI_R_fszy-9t8-YRAazZb1dk8X3OpafyP0YbzH03GGqX33DV_psxUle5Klro6ek73f_5lvLLAgCuly323SzZeTOjBHC7SxKyNJUlG3G1dZNHWe3H3gKW5fCB3jC6RdH7ObYg70Ugc8bc4LAUbLwNhqsZx3VR7AcRGgDGs8lJAIkuzATblNOcgBOi24IuLMe5YPS3EV9C8gEMb2obdLQ064BzI9_cmTkFkG9fRTLolQ-LZQITc9EgXctbe8jm4Fy530IpA7y0MqJ8YmvBAcnLCiIpeHbg0dbglZpvuVygAWKr9Sc7yVR-WK0ZPeCmzYNES5nDNRcWyHGKASVDHIZcNBHKoAypsznCh3UEfDkU63KVrgxsfmSNg6KLOE6gumFNPcDbZL6DAKyJYRS0bPqeVhz69tn6-sYQMEnwufkn7GzlkIN0nZM5jbkOpyciIB3KQ4hZ1mCBWhWy4jtiNIvpudh7UxVzLiBcjdG1qNJu_Xlm41HwY4ugF9Wta-BZI9-qks7NX3Y2-06BFLI8gRdWjWdCU73awGIzaeW6kdwOCuhnxsGWDSfsIkTETqhjNxZ84JN2WxhoHJnOd4IAtJmF-sdoiHgojq4-LHNIZH0LSpKDNLU=w1686-h948-no

Homer

**Comment by jrbudda** [comment]
Someone on the forums claimed this was caused by a conflict with transfer window planner. I cannot reproduce it and have no idea of the cause, if you or anyone else are able to give me steps to recreate the issue I will fix it.

**Comment by therealcrow999** [comment]
I think with me, once I deleted both settings.cfg from both mods I was fine. I believe I also had an old KER redux folder in my gamedata from the original mod and it had the settings.cfg in it. I think the old folder was called KER and now it is called KerbalEngineer. I think clearing out the old folder and deleting the settings.cfg, I got it working fine.
