### ISSUE TITLE
Wrong delta v with crossfeed enabled radial boosters

### ISSUE THREAD

**Issue by jj314** [jrbudda/KerbalEngineer#48]
Stage 0 of the following craft should have delta v but KER shows none. See the screenshot and attached craft file:

![image of craft](https://i.imgur.com/KOrVc4I.png)

craft file: https://pastebin.com/DMYcwT9u

**Comment by jrbudda** [comment]
No, you're burning all 3 engines in s1.

**Comment by jj314** [comment]
Yes but that doesn't mean that I want to hold on to the engines until they run out of fuel to burn. I want to detach the radial tanks as soon as they are empty. What would I have to change in my staging?

**Comment by jj314** [comment]
Since crossfeed is enabled on the radial decouplers, as can be seen by the fuel flow overlay, the radial tanks will drain first. Therefore, assuming that staging occurs as soon as the radial tanks drain, the center tank will still have fuel left.

**Comment by jrbudda** [comment]
KER does not 'assume' you're going to stage in a particular way. It stages when the fuel runs out. Maybe the stock calculation is doing something more clever but I have no intention at this point to re-write that logic.
