### ISSUE TITLE
Wrong in 1.8

### ISSUE THREAD

**Issue by undivido** [jrbudda/KerbalEngineer#49]
In 1.8.0.2686 bad graphics.
For example, HUD.
![screenshot4](https://user-images.githubusercontent.com/56364085/67038027-4f6be380-f127-11e9-9faa-37bc949f977e.png)
![screenshot6](https://user-images.githubusercontent.com/56364085/67038028-4f6be380-f127-11e9-8fbe-408e84174b62.png)

**Comment by jrbudda** [comment]
I am working on the update for 1.8 now.

**Comment by jrbudda** [comment]
If this happens to anyone else a clean install usually fixes it.
