### ISSUE TITLE
Crash upon pressing RCS isp

### ISSUE THREAD

**Issue by jungfaha** [jrbudda/KerbalEngineer#6]
[Crash_2018-04-08_215546.zip](https://github.com/jrbudda/KerbalEngineer/files/1888405/Crash_2018-04-08_215546.zip)

Just pressed on RCS isp and then the game bugged out lost all the planets and was just staring into space.

Ill be checking if any of the mods conflict. ;)

Sincerely, respectfully. regards

**Comment by jrbudda** [comment]
Is this reproducible? I do not see anything related to KER in this crash. This output_log.text has no reference to the crash at all, is there a KSP.log file for it?

**Comment by jungfaha** [comment]
tried to reproduce it.. seems its gone. my bad for jumping the gun. Again thank you for your time.
Sincerely, respectfully regards.
