### ISSUE TITLE
[Feature Request] Separator

### ISSUE THREAD

**Issue by quade-ksp** [jrbudda/KerbalEngineer#62]
I would like the current Miscellaneous Separator element improved (or another one added) with a small vertical mark at its center.  This would allow it to be used to create custom HUDs which also serve as aiming reticles.  These are handy not just for shooting things, but also marking the center of screens for flight maneuvers.

**Comment by jrbudda** [comment]
added a crosshair

**Comment by quade-ksp** [comment]
Thank you, sir.
