### ISSUE TITLE
Jet engines' thrust prediction is wrong

### ISSUE THREAD

**Issue by rattit0** [jrbudda/KerbalEngineer#63]
The jet engines' thrust predicted by KER in VAB/SPH is wrong.
It seems that KJR use this fomular to calculate the thrust:
`Thrust = maxThrust * k_a * k_v`
where `k_a` is the multiplier from `atmCurve`, and `k_v` is from `velCurve`

However, the parameter `flowMultCap` and `flowMultCapSharpness` should also be taken into account.
If `k_a * k_v > flowMultCap`, then the multiplier should be reduced to
`flowMultCapSharpness / ((flowMultCapSharpness-1)/flowMultCap + 1/k)`
where `k = k_a * k_v`

By default `flowMultCapSharpness = 2`, therefore it just the harmonic mean of the original multiplier and the cap.

You may probably notice that, for example, the maximum thrust of RAPIER engine is 465.64kN at Mach 3.75, but KER gives 105kN * 8.5 = 892.5kN.
`flowMultCap` for RAPIER is 3.0, then the correct multiplier is
`2/(1/3 + 1/8.5) = 4.435`
`105kN * 4.435 = 465.65kN`
That is the correct answer.

**Comment by jrbudda** [comment]
Corrected this for 1.1.7.2
