### ISSUE TITLE
Not compatible with KSP 1.10

### ISSUE THREAD

**Issue by BackGrounder84** [jrbudda/KerbalEngineer#64]
Version 1.10 actual not supported. :-(

![image](https://user-images.githubusercontent.com/38347392/86259974-fb256880-bbbc-11ea-8cad-9bbd406f75a9.png)

KerbalEngineer - 1.1.7.1

**Comment by BackGrounder84** [comment]
Wrong Fork

**Comment by jrbudda** [comment]
yea thanks.
