### ISSUE TITLE
Delta V readouts not displaying / updating within the VAB after update 1.11

### ISSUE THREAD

**Issue by TupperWareContainer** [jrbudda/KerbalEngineer#66]
See title; update 1.11 broke the delta V readouts to where they only update once you re-open the craft by exiting the VAB and re-entering, could be a problem with initializing the variables

Readouts when entering the VAB:
![20201218140934_1](https://user-images.githubusercontent.com/58698430/102623777-e3ed1f80-40f7-11eb-8928-930933dfa652.jpg)
 
Readouts after adding an extra fuel tank to the craft:
![20201218141020_1](https://user-images.githubusercontent.com/58698430/102623896-0f700a00-40f8-11eb-9e9a-c16ee026455b.jpg)

I have tried re-installing Kerbal Engineer Redux but it did not fix the problem  

The delta V readouts only update when launching the craft or exiting and re-entering the VAB, otherwise it works fine when you actually launch the craft

**Comment by 602p** [comment]
I've observed this too. It seems related to crewed parts. Building a craft without a crewed part causes the dV calculation to work fine. Sometimes this can be worked around by re-rooting the craft to a non-crewed part.

I also observe a (probably related) issue where the vessel tab in engineer in flight does not render and when enabled seems to have a severe memory leak.

Here is an excerpt from the debug log after a minimal repro (command pod as root part with SRB under it):
```
[LOG 13:06:13.476] KerbalEngineer -> Exception SimManager.StartSimulation() // System.NullReferenceException: Object reference not set to an instance of an object
  at KerbalEngineer.Extensions.PartExtensions.getCrewAdjustment (Part part) [0x00072] in <df610534f02e44eabb2fe7c95c06a0aa>:0 
  at KerbalEngineer.VesselSimulator.PartSim.New (Part p, System.Int32 id, System.Double atmosphere, KerbalEngineer.LogMsg log) [0x001c9] in <df610534f02e44eabb2fe7c95c06a0aa>:0 
  at KerbalEngineer.VesselSimulator.Simulation.PrepareSimulation (KerbalEngineer.LogMsg _log, System.Collections.Generic.List`1[T] parts, System.Double theGravity, System.Double theAtmosphere, System.Double theMach, System.Boolean dumpTree, System.Boolean vectoredThrust, System.Boolean fullThrust) [0x00185] in <df610534f02e44eabb2fe7c95c06a0aa>:0 
  at KerbalEngineer.VesselSimulator.SimManager.StartSimulation () [0x000ba] in <df610534f02e44eabb2fe7c95c06a0aa>:0 
```

(this repeats many times.)

**Comment by jrbudda** [comment]
Thanks I've got 2 weeks vacation til new years and will take care of it.

**Comment by 602p** [comment]
To anyone else finding this thread, a temporary workaround I have been using: in `Physics.cfg` change `kerbalCrewMass` to `0.0`, `perSeatReduction` to `0.0` and `perCommandSeatReduction` to `0.049`. Then if using ModuleManager delete the MM cache files. If I understand the comments right this will mean all parts act as if they were fully occupied. It also causes KER to skip the code path that is erroring out for me, and it seems to work fine after this patch.

**Comment by Sinomen** [comment]
Related: Adding a Kerbal to a pod actually reduces the rocket's mass displayed in KER, removing a Kerbal increases the mass. Unrealistic mass of -2177kg per Kerbal (incl. jetpack and EVA chute). 
Only seems to happen loading pre-existing rockets, not with new builds. 
602p's workaround fixes this issue.

**Comment by SirDragonfire** [comment]
A bit more to it for me... At first KER seemed fine (Dv pane open in VAB, though I wasn't paying it attention launching a vetted ship). 
I first noticed the Burn button (in flight - already activated) was not displaying anything and would only expand the Flight Engineer window to the Edit + Manage buttons (as if there was no maneuver set). I clicked Edit and then exited the editing screen. The Flight Engineer pane 'minimized' to a small grey block. Back in the VAB the KER button wont open the Dv pane at all, the resources popup worked but the vessel popup did not. Relaunching the game did not bring any functionality back.

**Comment by KerbonautRecruit** [comment]
Hi everyone! I'm new to this. Where do I find this "Physics.cfg" ? I didn't see a file named like this in any of the folders in the zip file. I didn't download the separate Source Code since in the "ReadMe" it only says to download this zip file, uncompress it, and put it in the GameData folder inside the game's folder. Help?

**Comment by 602p** [comment]
@KerbonautRecruit it is next to `KSP_x64.exe` (in the folder containing `GameData` -if you installed it via steam it should be named `Kerbal Space Program`.)

**Comment by GHrynk** [comment]
Just for situational awareness, MJ is doing real-time dv updates in the VAB, but is having an issue where it's not counting current crew mass in calculations.  Sort of the opposite problem of 602p's solution - it thinks every crewed part is empty.  It's possible there may be a common data-polling solution for both mods.

**Comment by whiterook6** [comment]
Can confirm. KER on KSP 1.11 doesn't calculate delta v properly _sometimes_. I cannot tell what causes it to stop working, or to resume working.

Screenshot:
![screenshot21](https://user-images.githubusercontent.com/5151965/102924591-bfba7700-4446-11eb-81da-3c529a383b7f.png)

Current Mods:
A bunch of Near Future tech
KER
Kerbal Alarm Clock
EVE, Scatterer

**Comment by whiterook6** [comment]
Additional screenshots, in case they help: KER appears to crash when the Vessel view is open.

![screenshot22](https://user-images.githubusercontent.com/5151965/102928191-280c5700-444d-11eb-849d-d7e33b7f8ece.png)
![screenshot25](https://user-images.githubusercontent.com/5151965/102928210-30649200-444d-11eb-97b5-7f751c20c64d.png)

**Comment by qfilip** [comment]
Dunno if it's any help, but when it computes TWR, there is a difference between information given in staging section and vessel card. Judging by my rocket performance, vessel card information was correct

![kerdiff](https://user-images.githubusercontent.com/44530839/103043719-242c2200-457e-11eb-9899-75c640ac3248.jpg)
