### ISSUE TITLE
Unable to fine-tune orbital period on v1.1.8.2

### ISSUE THREAD

**Issue by zmpeg** [jrbudda/KerbalEngineer#70]
I noticed in the last release, kerbal engineer is not showing seconds for orbital period. From the release notes, this seems intentional. I just wanted to highlight that for orbital period, it is important to have even the thousands of a second. This helps get comnets properly in sync. 1h 3m or 1h 4m is not very helpful as an orbit like that could drift badly in just a few orbits. Please reconsider this change? If not feel free to close this issue.

v1.1.8.1:
![image](https://user-images.githubusercontent.com/455699/103490985-e4b2d080-4ddc-11eb-9696-926a0b9fd369.png)

v1.1.8.2:
![image](https://user-images.githubusercontent.com/455699/103491013-2cd1f300-4ddd-11eb-8686-ab4eadf100f1.png)

Also! Thank you for your awesome work keeping this mod updated!

**Comment by jrbudda** [comment]
Thanks I had a feeling someone would quickly come up with a reason to have
more accuracy in one or more of the readouts. I will look into providing
more digits in this readout and let me know of any others. I like the
change for the majority of readouts due to less text but dont want to take
it away where needed. I could also do an option to just show seconds .

**Comment by jrbudda** [comment]
I fixed 3 readouts in 1.1.8.3 just now. I'll close this but let me know if there are any other readouts that need the same treatment.

**Comment by LouisB3** [comment]
> I fixed 3 readouts in 1.1.8.3 just now. I'll close this but let me know if there are any other readouts that need the same treatment.

@jrbudda It would be good to have "Time to Atmosphere" as a precise readout. I use this to set up KAC alarms when returning from lunar orbit, so that I can return to the vessel a few minutes before reentry.
